Fixed bug with missing SSLError in imports
  File "/usr/lib/python2.6/dist-packages/apns.py", line 153, in _connect
    except SSLError, ex:
NameError: global name 'SSLError' is not defined